global:
  datacenter: ${dc_name}
  image: hashicorp/consul-enterprise:1.4.4-ent

ui:
  service:
    type: "null"

connectInject:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  storage: 10Gi
  storageClass: local-storage
  connect: true
  enterpriseLicense:
    secretName: cloudops-consul-license
    secretKey: consul-license